// -----------------------------
// 3. Root layout
// -----------------------------
// app/layout.tsx
import './globals.css'
import { Header } from './Header'
import { ThemeProvider } from '../lib/ThemeContext'

export const metadata = {
  title: 'Rock It Summer Sector Series',
  description: 'Track your climbs for the 2025 Summer Sector Series at Rock It Derwent Park',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen" style={{ backgroundColor: 'var(--background)', color: 'var(--foreground)' }}>
        <ThemeProvider>
          <div className="max-w-6xl mx-auto p-6">
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}

/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/