BEGIN;

CREATE TABLE competitions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    name        TEXT NOT NULL,
    is_current  BOOLEAN NOT NULL DEFAULT false
);

-- Only one competition can be current at a time.
CREATE UNIQUE INDEX competitions_one_current
    ON competitions (is_current)
    WHERE is_current = true;

ALTER TABLE climbs
    ADD COLUMN competition_id BIGINT REFERENCES competitions(id);

-- Replace the global unique on sector_tag_id with per-competition uniqueness.
ALTER TABLE climbs
    DROP CONSTRAINT climbs_sector_tag_id_key;

CREATE UNIQUE INDEX climbs_sector_tag_per_competition
    ON climbs (competition_id, sector_tag_id);

ALTER TABLE competitions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "competitions_select_all" ON competitions
    FOR SELECT USING (true);

CREATE POLICY "competitions_all_admin" ON competitions
    FOR ALL USING (is_admin());

INSERT INTO competitions (name) VALUES
    ('Summer Sector Series ''26'),
    ('Rock It Rope Series ''26');

-- Backfill existing climbs into Summer Sector Series '26.
UPDATE climbs
    SET competition_id = (SELECT id FROM competitions WHERE name = 'Summer Sector Series ''26');

-- Trigger: auto-assign the current competition to new climbs that don't
-- specify one explicitly.  Raises an exception if no competition is current,
-- so setters get a clear error rather than a silent NULL violation.
CREATE OR REPLACE FUNCTION climbs_assign_current_competition()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.competition_id IS NULL THEN
        SELECT id INTO NEW.competition_id
        FROM competitions
        WHERE is_current = true
        LIMIT 1;

        IF NEW.competition_id IS NULL THEN
            RAISE EXCEPTION 'No current competition is set. Mark a competition as current before adding climbs.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER climbs_assign_current_competition
    BEFORE INSERT ON climbs
    FOR EACH ROW EXECUTE FUNCTION climbs_assign_current_competition();

ALTER TABLE climbs ALTER COLUMN competition_id SET NOT NULL;

COMMIT;
