BEGIN;

-- ---------------------------------------------------------------
-- 1. competition_categories
--    Stores the available registration categories for each comp
--    (e.g. 'Youth', 'Open', 'Masters', 'Social').
-- ---------------------------------------------------------------
CREATE TABLE public.competition_categories (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id BIGINT NOT NULL REFERENCES public.competitions(id) ON DELETE CASCADE,
    name           TEXT NOT NULL,
    sort_order     INT NOT NULL DEFAULT 0,
    CONSTRAINT competition_categories_comp_name_unique UNIQUE (competition_id, name)
);

ALTER TABLE public.competition_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "categories_select_all"
    ON public.competition_categories FOR SELECT USING (true);

CREATE POLICY "categories_all_admin"
    ON public.competition_categories FOR ALL USING (public.is_admin());

GRANT ALL ON TABLE public.competition_categories TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.competition_categories_id_seq TO authenticated, service_role;

-- ---------------------------------------------------------------
-- 2. competition_registrations
--    Each profile explicitly registers for each competition and
--    receives a competitor number scoped to that competition.
--    category_id is nullable for comps that have no categories.
-- ---------------------------------------------------------------
CREATE TABLE public.competition_registrations (
    id                UUID DEFAULT gen_random_uuid() NOT NULL,
    profile_id        UUID NOT NULL REFERENCES public.profiles(profile_id) ON DELETE CASCADE,
    competition_id    BIGINT NOT NULL REFERENCES public.competitions(id) ON DELETE CASCADE,
    category_id       BIGINT REFERENCES public.competition_categories(id) ON DELETE SET NULL,
    competitor_number INT NOT NULL,
    registered_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT competition_registrations_pkey PRIMARY KEY (id),
    CONSTRAINT competition_registrations_profile_competition_unique
        UNIQUE (profile_id, competition_id),
    CONSTRAINT competition_registrations_competition_number_unique
        UNIQUE (competition_id, competitor_number)
);

ALTER TABLE public.competition_registrations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "registrations_select_authenticated"
    ON public.competition_registrations
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "registrations_all_admin"
    ON public.competition_registrations
    FOR ALL USING (public.is_admin());

GRANT ALL ON TABLE public.competition_registrations TO authenticated, service_role;

-- ---------------------------------------------------------------
-- 3. register_for_competition
--    Assigns the next sequential competitor_number for the given
--    competition and inserts the registration row.
--    Idempotent: returns the existing row if already registered.
--    p_category_id is optional; pass NULL for comps with no categories.
-- ---------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.register_for_competition(
    p_profile_id     UUID,
    p_competition_id BIGINT,
    p_category_id    BIGINT DEFAULT NULL
)
RETURNS TABLE (
    registration_id    UUID,
    competitor_number  INT,
    already_registered BOOL
)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
    v_existing_id       UUID;
    v_existing_num      INT;
    v_next_num          INT;
    v_registration_id   UUID;
BEGIN
    -- Verify the caller owns the profile
    IF NOT EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profile_id = p_profile_id
          AND user_id = auth.uid()
    ) THEN
        RAISE EXCEPTION 'Not authorised to register this profile';
    END IF;

    -- Verify the competition exists
    IF NOT EXISTS (
        SELECT 1 FROM public.competitions WHERE id = p_competition_id
    ) THEN
        RAISE EXCEPTION 'Competition % does not exist', p_competition_id;
    END IF;

    -- Verify category belongs to this competition (if provided)
    IF p_category_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.competition_categories
        WHERE id = p_category_id AND competition_id = p_competition_id
    ) THEN
        RAISE EXCEPTION 'Category % does not belong to competition %', p_category_id, p_competition_id;
    END IF;

    -- Return early if already registered (qualify column to avoid OUT-param ambiguity)
    SELECT cr.id, cr.competitor_number
      INTO v_existing_id, v_existing_num
      FROM public.competition_registrations cr
     WHERE cr.profile_id = p_profile_id
       AND cr.competition_id = p_competition_id;

    IF v_existing_id IS NOT NULL THEN
        RETURN QUERY SELECT v_existing_id, v_existing_num, true;
        RETURN;
    END IF;

    -- Serialise concurrent registrations for the same competition so that
    -- competitor numbers are assigned without gaps or duplicates.
    PERFORM pg_advisory_xact_lock(p_competition_id);

    SELECT COALESCE(MAX(cr.competitor_number), 0) + 1
      INTO v_next_num
      FROM public.competition_registrations cr
     WHERE cr.competition_id = p_competition_id;

    INSERT INTO public.competition_registrations
        (profile_id, competition_id, category_id, competitor_number)
    VALUES
        (p_profile_id, p_competition_id, p_category_id, v_next_num)
    RETURNING id INTO v_registration_id;

    -- Use v_next_num directly; RETURNING competitor_number would be ambiguous
    -- with the OUT parameter of the same name in RETURNS TABLE.
    RETURN QUERY SELECT v_registration_id, v_next_num, false;
END;
$$;

GRANT EXECUTE ON FUNCTION public.register_for_competition(UUID, BIGINT, BIGINT)
    TO authenticated, service_role;

-- ---------------------------------------------------------------
-- 4. leaderboard_stats (updated)
--    - p_competition_id is now required (no DEFAULT NULL).
--    - competitor_number comes from competition_registrations.
--    - Only registered profiles appear (INNER JOIN).
--    - Returns category_name from competition_categories.
--    - Must DROP first because return type changes (BIGINT → INT,
--      and new category_name column added).
-- ---------------------------------------------------------------
DROP FUNCTION IF EXISTS public.leaderboard_stats(BIGINT);

CREATE FUNCTION public.leaderboard_stats(p_competition_id BIGINT)
RETURNS TABLE (
    profile_id        UUID,
    user_id           UUID,
    competitor_number INT,
    comp_cohort       TEXT,
    age_category      TEXT,
    category_name     TEXT,
    total_sends       BIGINT,
    total_points      BIGINT,
    pumpfest_sends    BIGINT,
    pumpfest_points   BIGINT
) LANGUAGE sql SECURITY INVOKER STABLE AS $$
    SELECT
        p.profile_id,
        p.user_id,
        cr.competitor_number,
        p.comp_cohort,
        p.age_category,
        cc.name AS category_name,
        count(a.id) FILTER (
            WHERE a.sent = true
              AND c.competition_id = p_competition_id
        )::BIGINT AS total_sends,
        COALESCE(SUM(
            CASE
                WHEN a.sent = true
                 AND c.competition_id = p_competition_id
                THEN CASE WHEN lower(w.name::text) = 'pumpfest' THEN 2 ELSE 1 END
                ELSE 0
            END
        ), 0)::BIGINT AS total_points,
        count(a.id) FILTER (
            WHERE a.sent = true
              AND c.competition_id = p_competition_id
              AND lower(w.name::text) = 'pumpfest'
        )::BIGINT AS pumpfest_sends,
        COALESCE(SUM(
            CASE
                WHEN a.sent = true
                 AND c.competition_id = p_competition_id
                 AND lower(w.name::text) = 'pumpfest'
                THEN 2
                ELSE 0
            END
        ), 0)::BIGINT AS pumpfest_points
    FROM public.profiles p
    INNER JOIN public.competition_registrations cr
        ON cr.profile_id = p.profile_id
       AND cr.competition_id = p_competition_id
    LEFT JOIN public.competition_categories cc
        ON cc.id = cr.category_id
    LEFT JOIN public.ascents a ON a.profile_id = p.profile_id
    LEFT JOIN public.climbs  c ON c.id = a.climb_id
    LEFT JOIN public.walls   w ON w.id = c.wall
    GROUP BY p.profile_id, p.user_id, cr.competitor_number,
             p.comp_cohort, p.age_category, cc.name;
$$;

GRANT EXECUTE ON FUNCTION public.leaderboard_stats(BIGINT)
    TO anon, authenticated, service_role;

-- ---------------------------------------------------------------
-- 5. create_anonymous_ascent (updated)
--    Parameter type changes BIGINT → INT to match per-competition
--    numbers. Lookup now goes through competition_registrations for
--    the current active competition.
-- ---------------------------------------------------------------
DROP FUNCTION IF EXISTS public.create_anonymous_ascent(BIGINT, UUID, BOOLEAN);

CREATE OR REPLACE FUNCTION public.create_anonymous_ascent(
    p_competitor_number INT,
    p_climb_id          UUID,
    p_sent              BOOLEAN DEFAULT true
)
RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
    v_ascent_id      UUID;
    v_existing_id    UUID;
    v_profile_id     UUID;
    v_user_id        UUID;
    v_competition_id BIGINT;
BEGIN
    SELECT id INTO v_competition_id
    FROM public.competitions
    WHERE is_current = true
    LIMIT 1;

    IF v_competition_id IS NULL THEN
        RAISE EXCEPTION 'No active competition';
    END IF;

    SELECT cr.profile_id, p.user_id
      INTO v_profile_id, v_user_id
      FROM public.competition_registrations cr
      JOIN public.profiles p ON p.profile_id = cr.profile_id
     WHERE cr.competition_id = v_competition_id
       AND cr.competitor_number = p_competitor_number
    LIMIT 1;

    IF v_profile_id IS NULL THEN
        RAISE EXCEPTION
            'Competitor number % is not registered for the current competition',
            p_competitor_number;
    END IF;

    SELECT id INTO v_existing_id
    FROM public.ascents
    WHERE profile_id = v_profile_id AND climb_id = p_climb_id;

    IF v_existing_id IS NOT NULL THEN
        UPDATE public.ascents
           SET sent = p_sent
         WHERE id = v_existing_id
        RETURNING id INTO v_ascent_id;
    ELSE
        INSERT INTO public.ascents (user_id, profile_id, competitor_number, climb_id, sent)
        VALUES (v_user_id, v_profile_id, NULL, p_climb_id, p_sent)
        RETURNING id INTO v_ascent_id;
    END IF;

    RETURN v_ascent_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_anonymous_ascent(INT, UUID, BOOLEAN)
    TO anon, authenticated, service_role;

COMMIT;
